language: java
jdk:
- oraclejdk8
sudo: required

script: gradle runAllTestsInFirefox
branches:
only: master

notifications:
  email: true
  recipients:
  - carlos.gonzales@jalasoft.com
  - AT01@fundacion-jala.org
